config/routes.rb
Rails.application.routes.draw do



  get 'pdf/generate'

  root to: 'visitors#index'

  get 'cart/show/', to: 'cart#show', as: 'shopping_cart'
  get 'cart/add/:product_id', to: 'cart#create', as: 'add_to_cart'
  get 'cart/remove/:product_id', to: 'cart#remove', as: 'remove_from_cart'
  get 'cart/addproduct/:product_id', to: 'cart#add', as: 'add_product_to_cart'
  get 'cart/checkout/', to: 'cart#checkout', as: 'checkout'
  get 'cart/update_cart/', to: 'cart#update_cart', as: 'update_cart'
  get 'invoices', to:'cart#index_invoice', as: 'invoices'
  get 'invoices/:id', to:'cart#show_invoice', as: 'invoice'
  get 'invoice/generate/:id', to: 'pdf#generate', as: 'generate_pdf'
  get 'my_products', to: 'cart#list_owned_products', as: 'my_products'
  devise_for :users
  resources :cart
  resources :orders
  resources :products
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :orders
  has_many :products, through: :orders
  has_many :shopping_carts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_filter :extract_shopping_cart, except: [:show_invoice, :index_invoice]
  before_action :authenticate_user!, only: [:checkout]
  def show
  end

  def index
  end

  def show_invoice
    @invoice = ShoppingCart.find(params[:id])
  end

  def index_invoice
    @invoices = current_user.shopping_carts
  end

  def create
    session[:checkout] = true
    product = Product.find(params[:product_id])
    @shopping_cart.buy_product(product)
    redirect_to shopping_cart_path, notice: "Thank you for purchasing our product"
  end

  def checkout

    flag = false
    @product_ids = ''
    @shopping_cart.shopping_cart_items.each do |item|
      @product_ids << "#{item.item_id},"
    end
    @products = Product.where(id: @product_ids[0...-1]).to_a
    current_user.products.each do |product|
      flag = true if @products.include? product
    end
    if flag == true
      redirect_to products_path, alert: "at least one of the products in shopping cart is already in your possesion or cart was empty"
    else
      @order = Order.new
    end
  end

  def remove
    @product = Product.find(params[:product_id])
    @shopping_cart.remove(@product, 1)
    redirect_to shopping_cart_path
  end

  def add
    @product = Product.find(params[:product_id])
    @shopping_cart.add(@product, @product.price)
    respond_to do |format|
      format.json {head :no_content}
      format.js
    end
  end

  def update_cart
  end

  def list_owned_products
    @shopping_carts = current_user.shopping_carts.includes(:shopping_cart_items => [:item])
  end

  def update
    respond_to do |format|
      session[:country] = Country.find_country_by_alpha2(shopping_cart_params[:country])
      if @shopping_cart.update(shopping_cart_params)
        format.html { redirect_to checkout_path, notice: 'Vat and address was successfully added!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def extract_shopping_cart
    shopping_cart_id = session[:shopping_cart_id]
    if ShoppingCart.exists?(id: session[:shopping_cart_id])
      @shopping_cart = ShoppingCart.find(shopping_cart_id)
    else
      session[:shopping_cart_id] = nil
      @shopping_cart = ShoppingCart.create
    end
    session[:shopping_cart_id] = @shopping_cart.id
  end

  def shopping_cart_params
    params.require(:shopping_cart).permit(:vat_id, :address, :city, :zip, :country)
 end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_form.html.erb
<%= simple_form_for @shopping_cart do |f| %>
<%= f.input :vat_id %>
<%= f.input :city %>
<%= f.input :zip %>
<%= f.input :country %>
<%= f.input :address %>
<%= f.button :submit %>
<% end %>

app/views/cart/add.js.erb
quantity = parseInt($('#item-<%= @product.id %> > td:nth-child(2)').text());
quantity += 1;
$('#item-<%= @product.id %> > td:nth-child(2)').text(quantity);
$('#price > h3').text('<%= @shopping_cart.total %>');

app/views/cart/checkout.html.erb
<% if !current_user %>
<h1> You have to be a logged user to proceed </h1>
<%= link_to 'Register', new_user_registration_path, class: 'btn btn-info' %>
<%= link_to 'Login', new_user_session_path, class: 'btn btn-info' %>
<% else %>
<div class="row">
       <div class="col-xs-12">
           <div class="text-center">
               <i class="fa fa-search-plus pull-left icon"></i>
               <h2>Order for purchase <%= @shopping_cart.check_vat_id %></h2>
           </div>

           <div class="row">
               <div class="col-xs-12 col-md-3 col-lg-3">
                   <div class="panel panel-default height">
                       <div class="panel-heading">Billing Details</div>
                       <div class="panel-body">
                           <strong><%= current_user.name %></strong><br>
                           Address: <%= @shopping_cart.address %><br>
                           Country: <%= session[:country] %><br>
                           ZIP: <%= @shopping_cart.zip %>

                       </div>
                   </div>
               </div>
               
           </div>
       </div>
   </div>
<div class="row">
  <div class="col-md-12">
      <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="text-center"><strong>Order summary</strong></h3>
          </div>
          <div class="panel-body">
              <div class="table-responsive">
                  <table class="table table-condensed">
                      <thead>
                          <tr>
                              <td><strong>Item Name</strong></td>
                              <td class="text-center"><strong>Item Price</strong></td>
                          </tr>
                      </thead>
                      <tbody>
                        <% @shopping_cart.shopping_cart_items.each do |item| %>
                        <% if !current_user.products.include? item %>

                        <tr>
                            <td><%= item.name %></td>
                            <td class="text-center">$<%= item.price %></td>
                        </tr>

                        <% else %>
                        <% @shopping_cart.total = @shopping_cart.total - item.price %>
                        <% end %>
                          <% end %>
                          <tr>
                              <td class="highrow"></td>
                              <td class="highrow"></td>
                              <td class="highrow text-center"><strong> <%= @shopping_cart.check_country_vat %></td> </strong>

                              <td class="highrow text-right"><%= @shopping_cart.subtotal %></td>
                          </tr>

                          <tr>
                              <td class="emptyrow"><i class="fa fa-barcode iconbig"></i></td>
                              <td class="emptyrow"></td>
                              <td class="emptyrow text-center"><strong>Total
                              </strong></td>
                              <td class="emptyrow text-right"><strong><%= @shopping_cart.total %></strong></td>
                          </tr>


                      </tbody>
                  </table>
              </div>
          </div>
      </div>

<%= simple_form_for @order do |f| %>
<%= f.input :vat_id, as: :hidden, input_html: { value: @shopping_cart.vat_id} %>
<%= f.input :address , as: :hidden, input_html: { value: @shopping_cart.address} %>
<%= f.input :shopping_cart, as: :hidden, input_html: { value: @shopping_cart.id} %>

<input type="hidden" name="product_ids" value="<%= @product_ids %>">
<%= f.input :total_payment , as: :hidden, input_html: { value: (@shopping_cart.total * 100).to_i} %>
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_OzSce5u3yDgLNsSugkbG9Ed1"
    data-amount="<%= @shopping_cart.total * 100 %>"
    data-name="Demo Site"
    data-description="Payment for invoice <%= @shopping_cart.vat_id %>"
    data-image="/128x128.png">
  </script>


<% end %>
  </div>
</div>

<% end %>

app/views/cart/index_invoice.html.erb
<% @invoices.each do |invoice| %>
<%= link_to invoice.vat_id, invoice_path(invoice) %>
<%= link_to 'Generate PDF', generate_pdf_path(invoice, format: 'pdf'), class: "btn btn-info" %>
<% end %>

app/views/cart/list_owned_products.html.erb
<% @shopping_carts.each do |cart| %>
  <% cart.shopping_cart_items.each do |item| %>
    <%= link_to item.name, product_path(item) %>
    <% end %>
  <% end %>

app/views/cart/remove.js.erb
quantity = parseInt($('#item-<%= @product.id %> > td:nth-child(2)').text());
quantity -= 1;
$('#item-<%= @product.id %> > td:nth-child(2)').text(quantity);
$('#price > h3').text('<%= @shopping_cart.total %>');

app/views/cart/show.html.erb
<table class="table table=stripped">
  <tr>
    <th>Name</th>
    <th>Action</th>
<% @shopping_cart.shopping_cart_items.each do |item| %>
<tr id="item-<%= item.item_id%>">
<td><%= item.name %></td>
<td>
<%= link_to 'remove', remove_from_cart_path(item.item_id), class: 'btn btn-danger' %>
</td>
</tr>
<% end %>
</table>
<div class="span6 pull-right" id="price">
<h2>
  Price without VAT
</h2>
<h3>
<%= @shopping_cart.subtotal %>
</h3>
<%= link_to 'Checkout', update_cart_path, class: 'btn btn-success' %>
</div>

app/views/cart/show_invoice.html.erb
      <div class="row">
        <div class="col-xs-6 col-xs-offset-5">
          <h1>INVOICE</h1>
          <h1><small><%= @invoice.check_vat_id %></small></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>From: Your Name
            </div>
            <div class="panel-body">
              <p>
              Your  Address <br>
              Your  details <br>
                more <br>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-5 col-xs-offset-2 text-right">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>To : <%= current_user.name %></h4>
            </div>
            <div class="panel-body">
              <p>
                <%= @invoice.address %> <br>
                <%= @invoice.city %>
                <%= @invoice.zip %> <br>
                <%= Country.find_country_by_alpha2(@invoice.country) %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- / end client details section -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>
              <h4>File</h4>
            </th>

            <th>
              <h4>Price</h4>
            </th>

          </tr>
        </thead>
        <tbody>
          <% @invoice.shopping_cart_items.each do |item| %>
          <tr>
            <td><%= item.name %></td>

            <td class="text-right"><%= item.price %></td>

          </tr>
          <% end %>

        </tbody>
      </table>
      <div class="row text-right">
        <div class="col-xs-2 col-xs-offset-8">
          <p>
            <strong>
            Sub Total : <br>
            TAX : <br>
            Total : <br>
            </strong>
          </p>
        </div>
        <div class="col-xs-2">
          <strong>
            <%= @invoice.subtotal %><br>
          <%= @invoice.check_country_vat %> <br>
          <%= @invoice.total %> <br>
          </strong>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h4>Bank details</h4>
            </div>
            <div class="panel-body">
              <p>Your Name</p>
              <p>Bank Name</p>
              <p>SWIFT : --------</p>
              <p>Account Number : --------</p>
              <p>IBAN : --------</p>
            </div>
          </div>
        </div>
        <div class="col-xs-7">
          <div class="span7">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4>Contact Details</h4>
              </div>
              <div class="panel-body">
                <p>
                  Email : you@example.com <br><br>
                  Mobile : -------- <br> <br>
                </p>
                <h4>Payment should be made by Bank Transfer</h4>
              </div>
            </div>
          </div>
        </div>
        <%= link_to 'Generate PDF', generate_pdf_path(@invoice, format: 'pdf'), class: "btn btn-info" %>
      </div>

app/views/cart/update_cart.html.erb
<h2>In order to finish the checkout, you have to provide your address and Vat_id</h2>


    <div class="col-xs-12 col-md-8 col-lg-8 col-lg-offset-2">
        <div class="panel panel-default height">
            <div class="panel-heading">Billing Details</div>
            <div class="panel-body">
              <%= render 'form' %>

            </div>
        </div>
    </div>