config/routes.rb
Rails.application.routes.draw do



  get 'pdf/generate'

  root to: 'visitors#index'

  get 'cart/show/', to: 'cart#show', as: 'shopping_cart'
  get 'cart/add/:product_id', to: 'cart#create', as: 'add_to_cart'
  get 'cart/remove/:product_id', to: 'cart#remove', as: 'remove_from_cart'
  get 'cart/addproduct/:product_id', to: 'cart#add', as: 'add_product_to_cart'
  get 'cart/checkout/', to: 'cart#checkout', as: 'checkout'
  get 'cart/update_cart/', to: 'cart#update_cart', as: 'update_cart'
  get 'invoices', to:'cart#index_invoice', as: 'invoices'
  get 'invoices/:id', to:'cart#show_invoice', as: 'invoice'
  get 'invoice/generate/:id', to: 'pdf#generate', as: 'generate_pdf'
  get 'my_products', to: 'cart#list_owned_products', as: 'my_products'
  devise_for :users
  resources :cart
  resources :orders
  resources :products
  resources :users
end

app/models/product.rb
class Product < ActiveRecord::Base
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def show

  end

  def index
    @products = Product.all
  end

  def create
  end

  def update
  end

  def new
  end

  def destroy
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_product.html.erb
<tr id="<%= product.name %>">
  <td><%= product.name %></td>
  <td><%= product.price %></td>
      <% if user_signed_in? %>
      <% if current_user.products.include? product %>
      <td><%= link_to 'Buy it!', add_to_cart_path(product.id), class: 'btn btn-success disabled' %></td>

  <% else %>
  <td><%= link_to 'Buy it!', add_to_cart_path(product.id), class: 'btn btn-info' %></td>
  <% end %>
  <% else %>
  <td><%= link_to 'Buy it!', add_to_cart_path(product.id), class: 'btn btn-success' %></td>
  <% end %>
</tr>

app/views/products/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Product#destroy</h1>
<p>Find me in app/views/product/destroy.html.erb</p>

app/views/products/index.html.erb
<table class="table table-stripped">
  <tr>
  <th>Name</th>
  <th>Price</th>
  <th>Buy</th>
  </tr>
  <%= render @products %>
</table>

app/views/products/new.html.erb
<h1>Product#new</h1>
<p>Find me in app/views/product/new.html.erb</p>

app/views/products/show.html.erb
<h1>Product#show</h1>
<p>Find me in app/views/product/show.html.erb</p>

app/views/products/update.html.erb
<h1>Product#update</h1>
<p>Find me in app/views/product/update.html.erb</p>