config/routes.rb
Rails.application.routes.draw do



  get 'pdf/generate'

  root to: 'visitors#index'

  get 'cart/show/', to: 'cart#show', as: 'shopping_cart'
  get 'cart/add/:product_id', to: 'cart#create', as: 'add_to_cart'
  get 'cart/remove/:product_id', to: 'cart#remove', as: 'remove_from_cart'
  get 'cart/addproduct/:product_id', to: 'cart#add', as: 'add_product_to_cart'
  get 'cart/checkout/', to: 'cart#checkout', as: 'checkout'
  get 'cart/update_cart/', to: 'cart#update_cart', as: 'update_cart'
  get 'invoices', to:'cart#index_invoice', as: 'invoices'
  get 'invoices/:id', to:'cart#show_invoice', as: 'invoice'
  get 'invoice/generate/:id', to: 'pdf#generate', as: 'generate_pdf'
  get 'my_products', to: 'cart#list_owned_products', as: 'my_products'
  devise_for :users
  resources :cart
  resources :orders
  resources :products
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= link_to shopping_cart_path do %>
        <li><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'My products', my_products_path %></li>
  <li><%= link_to 'Invoices', invoices_path %></li>

<% end %>
<li><%= link_to 'Products', products_path %> </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cart" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cart" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>